name: FASTAPI DEMO DEVOPS

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          apt-get update
          apt-get install -y libyaml-dev
          pip3 install --upgrade pip setuptools wheel cython
          pip3 install --no-cache-dir --prefer-binary -r requirements.txt

      - name: unittest
        run: |
          pytest test/test.py