name: FASTAPI DEMO DEVOPS

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          pip uninstall -y anyio fastapi starlette pydantic watchfiles
          pip install --only-binary :all: -r requirements.txt
          pip uninstall -y typing_extensions
          pip install --only-binary :all: typing_extensions==4.2.0

      - name: unittest
        run: |
          pytest test/test.py