name: FASTAPI DEMO DEVOPS

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          pip3 install --only-binary :all: -r requirements.txt
          pip install --upgrade pydantic fastapi
          pip install --upgrade fastapi starlette

      - name: unittest
        run: |
          pytest test/test.py