name: FASTAPI DEMO DEVOPS

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          apt update && apt upgrade -y
          apt install .build-deps gcc libc-dev make python3-dev py3-pip libffi-dev cython
          pip3 install --upgrade pip setuptools wheel cython
          pip3 install --no-cache-dir -r requirements.txt

      - name: unittest
        run: |
          pytest test/test.py